# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: torchft/marduk/marduk.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'torchft/marduk/marduk.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1btorchft/marduk/marduk.proto\"9\n\x0eRegisterDevice\x12\x13\n\x0b\x64\x65vice_uuid\x18\x01 \x01(\t\x12\x12\n\nreplica_id\x18\x02 \x01(\t\"!\n\nDrainEvent\x12\x13\n\x0b\x64\x65vice_uuid\x18\x01 \x01(\t\"&\n\x10ReplicaFailEvent\x12\x12\n\nreplica_id\x18\x01 \x01(\t\")\n\x12MonitoredFailEvent\x12\x13\n\x0b\x64\x65vice_uuid\x18\x01 \x01(\t\"F\n\x13\x43hangeTrConfigEvent\x12\x16\n\x0etr_config_type\x18\x01 \x01(\t\x12\x17\n\x0ftr_config_value\x18\x02 \x01(\t\"\x8c\x02\n\rEventEnvelope\x12\x0b\n\x03seq\x18\x01 \x01(\x04\x12\x10\n\x08ts_nanos\x18\x02 \x01(\x04\x12*\n\x0fregister_device\x18\t \x01(\x0b\x32\x0f.RegisterDeviceH\x00\x12\x1c\n\x05\x64rain\x18\n \x01(\x0b\x32\x0b.DrainEventH\x00\x12)\n\x0creplica_fail\x18\x0b \x01(\x0b\x32\x11.ReplicaFailEventH\x00\x12-\n\x0emonitored_fail\x18\x0c \x01(\x0b\x32\x13.MonitoredFailEventH\x00\x12\x30\n\x10\x63hange_tr_config\x18\r \x01(\x0b\x32\x14.ChangeTrConfigEventH\x00\x42\x06\n\x04\x62ody\"@\n\x15\x44\x65viceReplicaMapEntry\x12\x13\n\x0b\x64\x65vice_uuid\x18\x01 \x01(\t\x12\x12\n\nreplica_id\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'torchft.marduk.marduk_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERDEVICE']._serialized_start=31
  _globals['_REGISTERDEVICE']._serialized_end=88
  _globals['_DRAINEVENT']._serialized_start=90
  _globals['_DRAINEVENT']._serialized_end=123
  _globals['_REPLICAFAILEVENT']._serialized_start=125
  _globals['_REPLICAFAILEVENT']._serialized_end=163
  _globals['_MONITOREDFAILEVENT']._serialized_start=165
  _globals['_MONITOREDFAILEVENT']._serialized_end=206
  _globals['_CHANGETRCONFIGEVENT']._serialized_start=208
  _globals['_CHANGETRCONFIGEVENT']._serialized_end=278
  _globals['_EVENTENVELOPE']._serialized_start=281
  _globals['_EVENTENVELOPE']._serialized_end=549
  _globals['_DEVICEREPLICAMAPENTRY']._serialized_start=551
  _globals['_DEVICEREPLICAMAPENTRY']._serialized_end=615
# @@protoc_insertion_point(module_scope)
